### PR TITLE
Supports open action menu directly

### PR DESCRIPTION
**Pull request by hnvn**
Update `open` method to support open action menu directly without drag gesture

### CODE REVIEW

**Comment by miDeb** [comment]
I also made a workaround for this issue, so I know that just this change won't be enough.
The first problem here is that it will dismiss, not open (if if is dismissible). Secondly, you won't see an animation (at least not always).


Note that it is the plan to refactor this package (see [this issue](https://github.com/letsar/flutter_slidable/issues/41) and the `refactor` branch).

**Comment by letsar** [comment]
Thank you @miDeb . Yes I will not accept PR on the master branch for new features as long as I the refactoring is not finished. I have to document all the changes I've done but you can try the refactor branch if you want and look at the examples to know how to use the new APIs.

**Comment by miDeb** [comment]
With no secondaryActions, there are some bugs. Just look at this:

magic ✨!

btw saw you at flutter live!

**Comment by letsar** [comment]
Oh thanks @miDeb! It should be fixed now.
Oh you were also at Flutter live?

**Comment by miDeb** [comment]
No, I just watched the livestream...
Someone even used flutter_slidable if I remember well...

**Pull request closed without merging**
